Repository exDock/exDock-engine, pull requests merged in 2024-11, with the labels that each got.

#40 Create eventbus codec generator
  src/main/kotlin/com/ex_dock/ex_dock/database/JDBCStarter.kt
Labels: initialisation

#34 Expand template engine testing
  .github/workflows/tests.yml
  .idea/sqldialects.xml
  src/main/kotlin/com/ex_dock/ex_dock/database/connection/ConnectionPool.kt
  src/main/kotlin/com/ex_dock/ex_dock/frontend/template_engine/TemplateEngineVerticle.kt
  src/test/kotlin/com/ex_dock/ex_dock/frontend/template_engine/TemplateEngineVerticleSingleUseTest.kt
  src/test/kotlin/com/ex_dock/ex_dock/frontend/template_engine/TemplateEngineVerticleTest.kt
Labels: code quality

#44 Templates and blocks to the db table
  database/ex-dock.sql
Labels: initialisation

#43 Fixed getConnection not working correctly
  src/main/kotlin/com/ex_dock/ex_dock/ClassLoaderDummy.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/category/CategoryJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/connection/ConnectionPool.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductCompleteEavJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductCustomAttributesJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductGlobalEavJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductMultiSelectJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductStoreViewEavJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductWebsiteEavJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/scope/ScopeJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/server/ServerJDBCVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/text_pages/TextPagesJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/url/UrlJdbcVerticle.kt
Labels: bug

#41 Custom authentication provider to secure the web pages and resources
  database/ex-dock.sql
  pom.xml
  src/main/kotlin/com/ex_dock/ex_dock/MainVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/account/AccountClasses.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/account/AccountJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/frontend/account/router/accountRouter.kt
  src/main/kotlin/com/ex_dock/ex_dock/frontend/auth/AuthHandler.kt
Labels: enhancement, initialisation
