Repository exDock/exDock-engine, pull requests merged in 2024-12, with the labels that each got.

#48 Template engine caching
  src/main/kotlin/com/ex_dock/ex_dock/MainVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/account/AccountJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/category/CategoryJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductCustomAttributesJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductGlobalEavJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductMultiSelectJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductStoreViewEavJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductWebsiteEavJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/scope/ScopeJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/server/ServerJDBCVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/service/ServiceData.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/service/ServiceVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/template/TemplateClasses.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/template/TemplateJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/text_pages/TextPagesJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/url/UrlJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/frontend/cache/CacheHelperFunctions.kt
  src/main/kotlin/com/ex_dock/ex_dock/frontend/cache/CacheVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/frontend/template_engine/TemplateEngineVerticle.kt
Labels: enhancement

#52 Backend auth
  Dockerfile
  compose.yaml
  pom.xml
  src/main/kotlin/com/ex_dock/ex_dock/MainVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/backend/BackendRouter.kt
  src/main/kotlin/com/ex_dock/ex_dock/backend/v1/router/BackendV1Router.kt
  src/main/kotlin/com/ex_dock/ex_dock/backend/v1/router/auth/AuthProvider.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/JDBCStarter.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/account/AccountClasses.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/account/AccountJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/service/ServiceVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/frontend/auth/AuthHandler.kt
  src/test/kotlin/com/ex_dock/ex_dock/TestMainVerticle.kt
  src/test/kotlin/com/ex_dock/ex_dock/database/account/AccountJdbcVerticleTest.kt
Labels: enhancement, initialisation

#53 Upgrade helper functions
  .ci/compose.yaml
  .idea/sqldialects.xml
  src/main/kotlin/com/ex_dock/ex_dock/ExtensionsLauncher.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/JDBCStarter.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/account/AccountJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/codec/GenericCodec.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/codec/GenericListCodec.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/connection/ConnectionPool.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductClasses.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/database/product/ProductMultiSelectJdbcVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/frontend/account/AccountFrontendVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/frontend/account/router/accountRouter.kt
  src/main/kotlin/com/ex_dock/ex_dock/frontend/template_engine/TemplateEngineVerticle.kt
  src/main/kotlin/com/ex_dock/ex_dock/helper/VerticleDeployHelper.kt
  src/main/kotlin/com/ex_dock/ex_dock/helper/register_codecs.kt
  src/test/kotlin/com/ex_dock/ex_dock/database/account/AccountJdbcVerticleTest.kt
  src/test/kotlin/com/ex_dock/ex_dock/database/category/CategoryJdbcVerticleTest.kt
  src/test/kotlin/com/ex_dock/ex_dock/database/product/ProductCustomAttributesJdbcVerticleTest.kt
  src/test/kotlin/com/ex_dock/ex_dock/database/product/ProductGlobalEavJdbcVerticleTest.kt
  src/test/kotlin/com/ex_dock/ex_dock/database/product/ProductJdbcVerticleTest.kt
  src/test/kotlin/com/ex_dock/ex_dock/database/product/ProductMultiSelectJdbcVerticleTest.kt
  src/test/kotlin/com/ex_dock/ex_dock/database/product/ProductStoreViewEavJdbcVerticleTest.kt
  src/test/kotlin/com/ex_dock/ex_dock/database/product/ProductWebsiteEavJdbcVerticleTest.kt
  src/test/kotlin/com/ex_dock/ex_dock/database/scope/ScopeJdbcVerticleTest.kt
  src/test/kotlin/com/ex_dock/ex_dock/database/server/ServerJdbcVerticleTest.kt
  src/test/kotlin/com/ex_dock/ex_dock/database/text_pages/TextPagesJdbcVerticleTest.kt
  src/test/kotlin/com/ex_dock/ex_dock/database/url/UrlJdbcVerticleTest.kt
Labels: code quality
